$(".mrpiffls").click(function(){
    $(".disappear").toggle();
});
$(".piff").click(function(){
    $(".me").fadeToggle();
});
$(".bye").click(function(){
    $(".person").slideUp();
});
$(".hi").click(function(){
    $(".appear").slideDown();
});
$(".float").click(function(){
    $(".penny").toggle();
});